name: CI on push or pull request for python 3.8

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
    - name: Test notebooks with pytest + nbmake
      run: |
        pytest --nbmake  "dataset_splitting.ipynb" "coco2voc.ipynb" "yolo2coco.ipynb" "yolo2voc.ipynb"
